---
runner_version: "2.329.0"
runner_user: "runner"
runner_dir: "/home/{{ runner_user }}/actions-runner"
# Token should be provided via secrets.fact
github_pat: "{{ ansible_local.secrets.secrets.github_pat | default('') }}"
repo_url: "{{ ansible_local.secrets.secrets.github_repo_url | default('https://github.com/yrodrigez/ev_infra') }}"
